version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  go-app:
    image: pack-size-optimizer:latest
    container_name: go-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./path/to/your/local/code:/app    # Mount local code directory into the container

volumes:
  mysql_data: